<a href="https://colab.research.google.com/github/JCaballerot/Programacion-en-Python/blob/main/modulo_2/3.%20Numpy%20I_revisado_en_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >

<h1 align=center><font size = 5> Numpy - Parte I
</font></h1>

---

## Tabla de Contenidos

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>
    
1. <a href="#item31">Trabajando con arrays </a>
2. <a href="#item31">Algebra Matricial con arrays</a>  

</font>
</div>

---

# 1. Trabajando con Arrays 

In [1]:
import numpy as np

In [ ]:
#importando numpy
import numpy as np

In [ ]:
type(np.array([30, 25, 33, 24, 28, 32]))




numpy.ndarray

In [ ]:
np.array(['john', 'marco', 'diego'])

array(['john', 'marco', 'diego'], dtype='<U5')

In [ ]:
np.array([30, 25, 33, 24, 28, 32])

array([30, 25, 33, 24, 28, 32])

In [ ]:
np.array([30, 25, 33, 24, 28, 32],
         [ 8,  3, 10,  1,  5,  9])

TypeError: ignored

In [ ]:
a = np.array([[30, 25, 33, 24, 28, 38],

              [ 8,  3, 10,  1,  5,  9]])


In [ ]:
a

array([list([30, 25, 33, 24, 28]), list([8, 3, 10, 1, 5, 9])],
      dtype=object)

In [ ]:
a = np.array([[[30, 25, 33, 24, 28, 38],
               [ 8,  3, 10,  1,  5,  9],
               [ 5,  6,  5,  7,  5,  4]], 
              [[30, 25, 33, 24, 28, 38],
               [ 8,  3, 10,  1,  5,  9],
               [ 5,  6,  5,  7,  5,  4]]])


In [62]:
a = np.array([[[[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],
              
               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],
              
               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],
              
               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]],
              
               [[1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [1, 2, 3, 4,  5],
                [3, 4, 6, 8, 10],
                [6, 7, 8, 10, 2]]]])



print(a)

[[[[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]

  [[ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 1  2  3  4  5]
   [ 3  4  6  8 10]
   [ 6  7  8 10  2]]]]


In [ ]:
# Array de una dimensión
a1 = np.array([1, 2, 3])
print(a1)

In [ ]:
# Array de dos dimensiones
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

In [ ]:
# Array de tres dimensiones
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)

### Otras formas de crear arrays

In [ ]:
np.zeros((2, 2))

In [19]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.full((3, 3), 99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [24]:

np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.arange(1, 15 + 1, 3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
np.arange(1, 15 + 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [39]:
# linspace(start, end, n) genera n valores entre el valor start y el valor end
np.linspace(1, 10, 5)


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [50]:
np.random.random?

In [49]:
np.random.random((3, 3)) 

array([[0.06722171, 0.41097194, 0.71345247],
       [0.55150496, 0.13919446, 0.06107904],
       [0.92904352, 0.12965094, 0.51380023]])

In [53]:
np.random.randint(99)

47

In [55]:
np.array([np.random.randint(100) for x in range(0,5)])

array([35, 13,  8, 89, 99])

### Atributos de un array

In [60]:
my_array = np.identity(5)

In [64]:
my_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
#Devuelve el número de dimensiones del array
my_array.ndim

2

In [63]:
a.ndim

4

In [ ]:
5

In [66]:
#Devuelve una tupla con las dimensiones del array
my_array.shape


(5, 5)

In [67]:
a.shape

(1, 5, 5, 5)

In [ ]:
a

In [70]:
#Devuelve el número de elementos del array
my_array.size

25

In [71]:
a.size

125

In [72]:
#Devuelve el tipo de datos de los elementos del array
a.dtype

dtype('int64')

In [90]:
b = np.array(['john', 'jose', 'pablo', 'jose2', 'diegoooooooooooooooooooooooooo'])


In [86]:
b = np.array(['John', 'Marco'])

In [91]:
b.dtype

dtype('<U30')

In [77]:
type(5.0)

float

In [73]:
type(a)

numpy.ndarray

In [114]:

b = np.array([1_111_111_111_111_111_111, 'ab'])
b.dtype


dtype('<U21')

### Acceder a elementos del array

In [115]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a[1, 0])

4


In [116]:
# Cuál será la forma de extraer el valor 3 del array

a[0, 2]


3

In [117]:
# Cuál será la forma de extraer el valor 6 del array
a[1, 2]

6

In [126]:
a = np.array([[[1, 2, 3], [4, 5, 6], [4, 5, 6]],
              [[1, 2, 3], [4, 5, 99], [4, 5, 6]]])


In [131]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 4,  5, 99],
        [ 4,  5,  6]]])

In [132]:
a.shape

(2, 3, 3)

In [134]:
a.ndim

3

In [120]:
a[1, 1, 2]

99

In [130]:
a[1][1][2]

99

In [122]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1][0])


4


In [125]:
a[0][2]

3

In [ ]:
print(a[:, 0:2])

In [147]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 7, 8]])

a[:, 3:]


array([[4, 5],
       [7, 8]])

In [145]:
a

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 7, 8]])

In [140]:
a.shape

(2, 5)

In [148]:
a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 7, 8], [10, 11, 30, 77, 18]])
a

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  7,  8],
       [10, 11, 30, 77, 18]])

In [ ]:
[[ 3,  7],
 [30, 77]]

In [149]:
a.shape

(3, 5)

In [150]:
a[1:, 2:4]


array([[ 3,  7],
       [30, 77]])

### Filtrado de elementos de un array

In [159]:
a = np.array([[1, 2, 3, 8], [4, 5, 6, 7]])

temp = a[(a%2 == 0)]

temp.reshape(2,2)


array([[2, 8],
       [4, 6]])

In [154]:
a = a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape


(2, 3)

In [161]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[(a % 2 == 0) & (a > 2) & (a < 6)])

[4]


In [163]:
ciudad_1={'nombre':'Lima',
          'Pais':'Perú',
          'población':'10 MM',
          'Hecho':'Tiene el mejor ceviche y está en el mercado el Eden', 
          }
ciudad_2={'nombre':'La Paz',
          'Pais':'Bolivia',
          'población':'1 MM',
          'Hecho':'Tiene la mejor salteña y es la Ortis', 
          }
ciudad_3={'nombre':'Santa Cruz',
          'Pais':'Bolivia',
          'población':'3 MM',
          'Hecho':'Tiene el mejor arroz con queso y esta en la casa del Camba', 
          }
Ciudades = [ciudad_1,ciudad_2,ciudad_3]

for ciudad in Ciudades:
  print(ciudad.get('nombre'), 'pertenece a', ciudad.get('Pais'), 'tiene una poblacion de', ciudad.get('población'))



Lima pertenece a Perú tiene una poblacion de 10 MM
La Paz pertenece a Bolivia tiene una poblacion de 1 MM
Santa Cruz pertenece a Bolivia tiene una poblacion de 3 MM


In [ ]:
print(a[(a % 2 == 0) &  (a > 2)])

### Operaciones matemáticas con arrays

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1, 1], [2, 2, 2]])

In [ ]:
print(a + b )

In [ ]:
print(a / b)

In [ ]:
print(a ** 2)

# 2. Álgebra matricial con arrays

### Producto escalar de dos vectores

u.dot(v): Devuelve el producto escalar de los vectores u y v.



In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([1, 0, 1])
print(a @ b)

In [ ]:
print(a.dot(b))

In [ ]:
a*b

### Módulo de un vector

norm(v): Devuelve el módulo del vector v.

In [ ]:
a = np.array([3, 4])

In [ ]:
print(np.linalg.norm(a))

### Producto de dos matrices

a.dot(b) : Devuelve el producto matricial de las matrices a y b siempre y cuando sus dimensiones sean compatibles.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [2, 2], [3, 3]])
print(a @ b)

In [ ]:
print(a.dot(b))

### Matriz traspuesta

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

### Traza de una matriz

a.trace() : Devuelve la traza (suma de la diagonal principal) de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.trace())

### Determinante de una matriz

det(a) : Devuelve el determinante de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))

### Matriz inversa

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(a))

### Autovalores de una matriz


eigvals(a) : Devuelve los autovalores de la matriz cuadrada a.



In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eigvals(a))

### Autovectores de una matriz

eig(a) : Devuelve los autovalores y los autovectores asociados de la matriz cuadrada a.

In [ ]:
a = np.array([[1, 1, 0], [1, 2, 1], [0, 1, 1]])
print(np.linalg.eig(a))

solve(a, b) : Devuelve la solución del sistema de ecuaciones lineales con los coeficientes de la matriz a y los términos independientes de la matriz b.

In [ ]:
# Sistema de dos ecuaciones y dos incógnitas
# x + 2y = 1
# 3x + 5y = 2 
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
print(np.linalg.solve(a, b))


### Solución de un sistema de ecuaciones

---

# Gracias por completar este laboratorio!

---
